vespa-engine/cloud

automated-deployments.html, reference/vespa-cloud-api.html
When we link to `console.vespa.ai`, we must use https-less links.
=> console.vespa.ai's redirect does not support https yet

getting-started.html
- use clients.pem for this to work
- cert generation non-interactive for later test automation
- https git download
=> minor fixes

reference/deployment.html
Removing `<notifications>` element from documentation until the feature works.
=> Remove notifications from deployment.xml reference

security-model.html
tested myself, it works - thanks !!!
I suggest I change the certificate CN to _cloud.vespa.example_ in the guides, unless you have other opinions (that should never collide with anything ...) - and then update this guide as well
=> add browser procedure for certs

status.json
Adding "last updated" information to JSON output. Unfortunately, I wasn't able to add this information into the existing JSON structure, so I needed to wrap the previous status info into an additional `status` JSON object.
New format:
```javascript
{
"last-update": "1587726680",
"status": {
"messages": [
{
"date": "2020-03-23",
"message": "The aws-ap-northeast-1a zone in Tokyo, JP region is now online!"
}
],
"zones": [
{
"message": "OK",
"name": "Infrastructure",
"status": "success"
},
{
"message": "OK",
"name": "aws-us-east-1c",
"status": "success"
},
{
"message": "OK",
"name": "aws-ap-northeast-1a",
"status": "success"
}
]
}
}
```
=> Add last updated timestamp to status JSON

getting-started.html
cannot easily replace the git clone, as the auto testing uses it - and the repo must be cloned from somewhere anyway - so maybe this is best compromise
=> add generate link

faq.html
Objectives:
* better self-serve
* easier way to make content searchable - the FAQ is a light-weight way to add terms that users use, that not necessarily belong in regular doc
I tried writing this in markdown and auto-generate the TOC - that would cut the text by 30%. It was however hard to customise, and the TOC is the critical part - users browse to see if his/her question is already answered, so this must be good. Hence hard-coded.
I would like to improve the format of the rest of the FAQ as well in later PRs but lets get started / get som feedback
=> first cut FAQ

_layouts/default.html, css/docs.css, faq.md
@kkraune Please review and let me know what you think. Made FAQ back to markdown with auto-generated TOC for easier maintenance and styled the TOC to be more or less identical with HTML style.
*Before:*
*After:*
=> FAQ as markdown and auto TOC with custom style

_includes/footer-wide.html, _includes/footer.html, _includes/nav.html, _layouts/page-wide.html, getting-started.html, guides.html, reference-documentation.html, use-cases.md
with this, all resources linked from current left frame is now reachable (in)directly from header/footer
lots of todo's, but content is not worse than before - but we can now decide to switch to new index page without the left frame in later PR
=> footer/header and guide/ref doc links

_data/sidebar.yml, _includes/sidebar.html
This is a suggestion - not sure if keep or not. Assuming we want to have a left bar for "documentation" articles like guides and references, this will work. Copied from vespa doc repo, but skipped the collapse logic for now, can add if we need to
note that there is some overlap in guide and ref doc, like the testing doc. not sure what is right. resolve later
=> group items in left nav

_includes/footer-wide.html, _layouts/page-wide.html
the only real change is not using footer style from docs.css (the rest is just simplifications):
* I don't like fixing the footer at the bottom (few sites uses it, and vespa.ai does not fix it)
* the footer style is confusing anyway - lets harmonize with vespa.ai down the road
I am inclined to add the footer in the page layout instead of including, as the layouts are so small anyway
=> do not use fixed footer

data-dump.html
continuation token is not emitted at end - this script does proper json parsing to get the token regardless
=> more robust data dump

index.html
@kkraune or @frodelu 
It's about time we switch to denali cause I've found a subset of bootstrap which predictably does what it says it should
I think the text in the first table and above is ok now (but layout should be changed a lot).
I want each of the table rows (i.e Vespa cloud "features") to point into the next sections of the document, and I'll work on that next. I removed the sections that didn't map to any of them (since they were more about Vespa than the cloud).
=> Somewhat better copy and layout

css/denali-theme-vespa-light.scss
@kkraune / @bratseth : This should fix the menu on mobile devices
=> Fix background colors for responsive menu on light pages

_layouts/redirect.html, en/automated-deployments.html, en/developer-guide.html, en/getting-started.html, en/getting-to-production.html, en/reference/deployment.html, en/reference/environments.html, en/security-model.html
- Removed the redirect template as it was creating issues. The default template seems to work.
- Added `redirect_from` to the resources that are referenced in Vespa and Console.
=> Redirect for legacy links that are used in console and vespa

support.html
The console refers to support, so we should have cloud.vespa.ai/support. This is the minimal to fix broken console links. 
This is also useful in other settings, when communicating over slack/email - "please use cloud.vespa.ai/support" ...
lets refine the looks in later PR @bratseth @frodelu 
@freva once merged, please check console
=> create /support resource

en/reference/zones.html
After moving console out of controller, we need to go different endpoint and path to reach the API.
Not sure why these are curl commands since the only way to access those APIs is with Auth0 cookies, which is not documented here and aren't that easy to use...
=> Remove /api/ and fix endpoint

en/reference/testing.html
It looks like the testing framework pick up username as instance, which it should not. Hence users should always provide instance name, added app name for completeness (app and tenant often set in pom.xml, but complicates doc with this, it will always work when testing in IDE)
=> supply instance as well

_data/status.yml, _plugins/utc_filter.rb, status.html
@bratseth / @kkraune : We can still do more styling to make it look better, but this gives us the functionality to (optionally) include time in status messages for more precision.
=> Allow for timestamps in status messages for more precision

en/monitoring.html
Link directly to Cloudwatch subdir in metrics-emitter (top level README very light-weight) and add a bit more text around link.
@kkraune please review.
=> Update link to metrics-emitter doc

en/getting-started-java.html, en/getting-to-production.html
Reverts vespa-engine/cloud#310
Console now downloads only the private key, name `USER.TENANTNAME.pem` and has a separate download button to download the public key (named `USER.TENANTNAME.pub.pem`. See VESPA-20874.
=> Revert "Update documentation for apiKeys in guide"
