_data/sidebar.yml, _includes/header.html, _includes/nav.html, css/docs.css, index.html
Reverts vespa-engine/cloud#4
Where's the sign-up page, @oyving ? Reverting change for now.
=> Revert "Move sign-up to separate page with email form"

_data/sidebar.yml, _includes/sidebar.html
@kkraune Please review
I've removed "top level" sidebar sections and ability to collapse. Also added ".html" in sidebar.yml to make highlighting current page work.
=> Flatten down sidebar to only support two non-colllapsible levels

getting-started.html
=> troubleshooting

_includes/nav.html
This does not search the cloud docs but lets fix that later
=> search docs.vespa.ai

_includes/nav.html
=> link to documentation

_data/sidebar.yml, _includes/header.html, _includes/nav.html, css/docs.css, index.html, sign-up.html
Re-introducing the changes from #4, but now fixing the issues with it.
=> Separate sign-up page and various fixes

getting-started.html
=> use rsa key

_data/sidebar.yml
selectively link to relevant documents in cloud.vespa.ai sidebar
=> link to use cases

getting-started.html
=> collapse into one step

ops-use-cases.md
=> split out node failures

ops-use-cases.md
=> split to more details

_data/sidebar.yml, use-cases.md
=> move used cases from doc to cloud

getting-started.html
=> Update terminology to Vespa Cloud.

elastic-search-comparison.md, migrating-from-elastic-search-to-vespa.md
=> fix broken links

elastic-search-comparison.md
=> remove broken link

reference/vespa-cloud-api.html
@smorgrav please review and merge.
=> Add "commit" as parameter to submissions

automated-deployments.html, reference/deployment.html
@kkraune please review and merge.
@tokle FYI.
=> Document required instance removal for deleting an application

status.html
=> Revert "Warn about maven central inconsistency"

reference/zones.html
=> fix typo + non-functional

reference/vespa-cloud-api.html
swap column order. had to cheat a little, putting some text about defaults in the comments column to make the mandatory column slimmer.
now columns are aligned and doc looks better
=> align column width

benchmarking.md
=> unbreak link

benchmarking.md
as there is little graph integration yet, dump metric to track progress
=> metric example

automated-deployments.html, reference/vespa-cloud-api.html
@kkraune please review. Depends on https://github.com/vespa-engine/vespa/pull/12268
=> Use new aliases for vespa versions

getting-started.html
=> link to security model

performance-use-cases.md
- the site is too slow, and we do not really _need_ to link, remove for now
=> fix link checker

getting-to-production.md
Updated after doing a test-run of prod. deployment
=> Add missing pom.xml properties step

index.html, ops-use-cases.md, pricing.html, use-cases.md
@kkraune please review.
Most "controversial" change is removing ellipsis on main hero section heading in favor of a full stop. To me, ending a sentence with "..." implies something remains untold. From a design perspective, a full stop may arguably be _too_ "bold" as its usage in a heading effectively says "and that's how it is, deal with it!" (Apple seems to love doing it, for instance), but that's not necessarily wrong. 🦄✨
=> Grammar nitpicks.

Gemfile, Gemfile.lock
=> more minimal

_data/sidebar.yml, automated-deployments.html, getting-to-production.md, reference/testing.html
=> split auto deployments

.github/workflows/feed.yml, .gitignore, Gemfile, _config.yml, _plugins/vespa_index_generator.rb, feed_to_vespa.py
- should think of a better solution than just copy files from vespa-engine/documentation, but works for now ... at least simple!
=> feed cloud docs to search

README.md
- same guidelines apply, remove superflous
=> badge, link to vespa doc

_layouts/default.html
makes no sense to have it here - and it will mute the link checker, too
=> no edit link for cloud

automated-deployments.html, reference/vespa-cloud-api.html, security-model.html
=> keys, refer to examples / GH actions workflow

automated-deployments.html
=> make it easier to integrate with secrets

_data/status.yml, status.html, status.json
=> Modelling site status as data and add JSON output

getting-started-custom-code.html
this will replace https://github.com/vespa-engine/sample-apps/blob/master/vespa-cloud/album-recommendation-java/README.md - it will link to here instead (as we agreed to)
not linked to yet, will auto test it first
=> first cut migrated guide

reference/vespa-cloud-api.html
simplify a little and document what is required for system/staging tests
=> mvn test requirements

getting-to-production.md
=> Link to Actions example, from first encountered mention

reference/services.html
=> Document autoscaling ranges

feed_to_vespa.py
=> add missing parameter

data-dump.html, migrating-from-elastic-search-to-vespa.md
will fix the python script in Vespa, too
=> less search def

migrating-from-elastic-search-to-vespa.md, security-model.html
=> track doc name change

_data/sidebar.yml, getting-to-production.md
=> link to guide

_data/status.yml
Reverts vespa-engine/cloud#114 - incident cleared
=> Incident cleared

getting-started-custom-code.html, reference/environments.html
=> vespa dev env and upgrades

getting-started.html
=> ignore link check

_config.yml, pricing.html
Redirect to /pricing so that we don't get 404
Also creating a PR to fix the Vespa code.
=> Code in Vespa points to /quota

reference/zones.html
=> add tokyo zone

getting-started-custom-code.html, reference/testing.html, reference/vespa-cloud-api.html
=> tenant-cd -> tenant-cd-api

security-model.html
@tokle please merge
@Oracien FYI
=> metrics API is data-plane

_data/status.yml
=> Application builds failing

_data/status.yml
=> Fix markup

config-prometheus-grafana.html
=> Moved over from documentation repo

config-prometheus-grafana.html
=> Update cloud monitoring

_data/sidebar.yml, _includes/footer.html, album-recommendation-searcher.html, getting-to-production.md, reference/testing.html, vespa-cloud-quick-start.html
=> use correct names

data-dump.html
=> tokens can be long

_config.yml
=> less noise regenerating

index-new.html
=> fix broken link and add alt-attributes

README.md, _config.yml, _data/sidebar.yml, _data/status.yml, _includes/sidebar.html, _layouts/default.html, _layouts/empty.html, _layouts/page.html, benchmarking.md, config-prometheus-grafana.html, elastic-search-comparison.md, migrating-from-elastic-search-to-vespa.md, ops-use-cases.md, performance-use-cases.md, pricing.html, reference/environments.html
=> nonfunctional: correct license

getting-started.html, guides.html, index-new.html, reference-documentation.html
=> remove local style

getting-started.html, index.html
Per Jon Feedback
moved from getting started and using more recent info from latest cloud slides.
=> vespa cloud highlights moved to index

getting-started.html
=> now with icons and a little more text

index.html
=> a little more compact, better looking

_plugins/vespa_index_generator.rb
this should improve summaries for search results from markdown docs
=> convert Markdown to HTML for text extract

album-recommendation-searcher.html
=> link to source repo

reference/testing.html
=> Add production test reference

automated-deployments.html, getting-to-production.md, reference/vespa-cloud-api.html
automated-deployments is still a bit half-baked, but the start is better and easier for people to get started. will rework the details in the end in later PR
=> push details to the end in automated-deployments

pricing.html
Hw keeps getting cheaper. @kkraune @frodelu @johans1
=> Adjust prices

album-recommendation-searcher.html, automated-deployments.html, benchmarking.md, developer-guide.md, elastic-search-comparison.md, faq.md, getting-started.html, getting-to-production.md, guides.html, index.html, migrating-from-elastic-search-to-vespa.md, model-serving.md, monitoring.md, ops-use-cases.html, performance-use-cases.html, pricing.html, reference-documentation.html, reference/deployment.html, reference/services.html, reference/vespa-cloud-api.html, reference/zones.html, security-model.html, status.html, support.html, use-cases.html, vespa-cloud-quick-start.html
=> clean up guides page + misc

benchmarking.md, guides.html, monitoring.md
=> better examples, text cleanup/format. Add to guide overview

reference/testing.html
=> make it easier to avoid local test problems

_data/status.yml
Reverts vespa-engine/cloud#194
=> Revert "Update infrastructure status"

_data/status.yml
=> Making customers aware of incident VESPA-19109

_data/status.yml
=> more details in status message

_data/status.yml
=> Update status for fixed incident

status.html
=> make a little nicer with a table view

getting-started.html, pricing.html
=> free trial

benchmarking.md, index.html
Sizing will be a separate document, and it will also include autoscaling. But I need to get autoscaling work first, so add doc here for now so we can link to for support
=> move sizing from index, add more details

_config.yml
=> Feed both instances for consistency

album-recommendation-searcher.html, getting-started.html, pricing.html
@frodelu 
let's spend some time on better describing the free trial (what it is , what you can do), starting from here. It is then easier for design team to add the visuals thereafter
=> better free trial description

reference/vespa-cloud-api.html
=> track link change

reference/vespa-cloud-api.html
=> track file move, update link

_includes/footer-wide.html, _includes/footer.html
ok when checked individually but then running on site we get _400 No error_. this is in the footer, hence in every page, so maybe that is why. disable for now
=> do not link check this for every page

support.html
=> no link check

index.html
@kkraune or @frodelu 
Layout is still not good but waiting to do more than patching
=> Fix some text and layout

index.html, security-model.html
=> use http://console.vespa.ai

.github/workflows/feed.yml
=> correct secret name

index.html
@kkraune or @frodelu make the page tolerable looking for now. The documented way to add margin/padding does not work.
=> Add whitespace

index.html, pricing.html
=> Pricing page fixes

reference/vespa-cloud-api.html
=> Add doc for the new suspend goal

album-recommendation-searcher.html
=> Add instance to deploy command in doc

reference/vespa-cloud-api.html
=> Update reference doc with instance being mandatory

benchmarking.md, model-serving.md
=> track page rename

migrating-from-elastic-search-to-vespa.md
The python conversion script fails on the mapping data, but that is a separate problem and I will get to it - this makes it easier to get the data needed and serve as an example. ElasticDump has moved repo and changed its install, so this is needed to make this part work
=> fix elasticdump using docker/npm and add sample data

getting-started.html
the page is a little crowded but we will get a new one any day now ...
=> same as on index page

migrating-from-elastic-search-to-vespa.md
now the guide works. next step is moving it to the open site and make it great
=> make guide work with example data

album-recommendation-searcher.html
=> set correct instance name

Gemfile
=> run the vespa index generator

en/autoscaling.html, en/reference/testing.html, pricing.html
=> correct broken links

en/getting-started-java.html
=> make auto testing work

en/dumping-data.html
=> Add update and remove examples using new features

en/dumping-data.html
=> fix formatting error

_includes/navbar.html
=> make search work from sub-pages

en/developer-guide.html, en/reference/environments.html, en/reference/zones.html
=> perf zone / env table fixes

_data/status.yml, status.html
ref https://github.com/vespa-engine/cloud/pull/260
=> add new zones to status

.github/workflows/feed.yml, _config.yml, search.html
@bratseth @frodelu  makes it similar to vespa.ai and speeds up the automation
=> vespa.ai results, gh action speedup / no deprecations

search.html
=> sample app hits

_plugins/vespa_index_generator.rb
!excluded.include will not win a coding prize ...
=> do not index generated redirect file

_data/features.yml
this is the text as-is - please add the other illustrations as well so we can iterate with Marco. @frodelu
=> from 8 to 6 items, text from spreadsheet

_plugins/vespa_index_generator.rb
thanks for finding this, @jobergum  !
=> exclude files from search

search.html
=> use YQL query and new endpoint

en/secret-store.html
=> Remove copy-pasted redirect_from statement

_data/status.yml
=> 2021 not 2020 MERGEOK

_data/status.yml
=> Quote to hide : MERGEOK

_data/status.yml
=> Flipping status MERGEOK

en/secret-store.html
=> Update the secret store xml syntax

en/secret-store.html
lets check in for now before next round of tests, easier to edit now
@tokle
=> wip - linebreaks for ediability + some more info added

404.html, _includes/cover.html, _includes/features.html, _includes/footer.html, _includes/htmlhead.html, _includes/image-modal.html, _includes/js.html, _includes/navbar.html, _layouts/frontpage.html, _layouts/page.html, index.md, status.html, status.json
=> Show title. copyright. page layout for 404

_data/status.yml
=> Notify users about auth0 outage

_includes/navbar.html
=> add missing link

_data/status.yml
=> auth0 outage is over

_data/status.yml, status.html, status.json
Created a new section for services in addition to zones, and added the console as a service in that section.
=> Add console as a service that we expose the status for

en/getting-started-java.html, en/getting-started.html
=> speed up download

_data/features.yml
=> simplify, fix broken sentence

pricing.html
@oyving or @bratseth  just in case
=> trial end data purge

_includes/footer.html, css/style.scss
@johans1 / @bratseth / @kkraune : Please review and merge.
=> Add link to privacy page in footer

_config.yml
=> remove unused

en/index.html, en/reference/endpoints.html
=> Add simple docs explaining structure of endpoints

_data/status.yml
@andreer Please confirm that public is affected and review message.
=> Warn about TLS certificate issues

_data/status.yml
=> Certificate generation recovered

en/getting-started-java.html, en/getting-to-production.html
=> Update documentation for apiKeys in guide

en/getting-started.html
There wasn't a corresponding separate bullet to link to so I removed the mvn reference at step 4.
=> Remove maven option here

en/reference/testing.html
=> username is not default for instance anymore

en/archive-guide.md
=> add guide for access log lambda

en/automated-deployments.html, en/getting-to-production.html
=> clarify app/instance removal
